---
# tasks file for iptables (CentOS specific)

- name: Install iptables packages
  become: yes
  yum:
    name: "{{ item }}"
    state: "{{ iptables_pkg_state }}"
  when: "{{ iptables_pkg_install }}"
  with_items:
    - "{{ iptables_packages }}"
