---
# tasks file for iptables

- include: params.yml
  tags:
    - 'role::iptables'
    - 'role::iptables::params'

- include: packages.yml
  tags:
    - 'role::iptables'
    - 'role::iptables::packages'

- include: services.yml
  tags:
    - 'role::iptables'
    - 'role::iptables::services'

- include: configs.yml
  tags:
    - 'role::iptables'
    - 'role::iptables::configs'
