---
# handlers file for iptables

- name: restart iptables
  become: yes
  service:
    name: "{{ iptables_service_name }}"
    state: restarted
  changed_when: config_result|changed
  tags:
    - iptables
